#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "   ___       ___       ___       ___    ";
$L "  /\  \     /\  \     /\  \     /\  \   ";
$L " /::\  \   /::\  \   /::\  \   /::\  \  ";
$L "/::\:\__\ /:/\:\__\ /:/\:\__\ /::\:\__\ ";
$L "\/\::/  / \:\/:/  / \:\:\/__/ \/\::/  / ";
$L "  /:/  /   \::/  /   \::/  /     \/__/  ";
$L "  \/__/     \/__/     \/__/             ";
$L "Welcome to Android `getprop ro.build.version.release` / Android Open Grand Project-`getprop ro.aogp.version`";
